spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务注册中心
    sentinel:
      # 必须关闭统一上下文，否则链路模式无法识别来源
      web-context-unify: false
      transport:
        dashboard: localhost:8080 #sentinel控制台地址
        port: 8719 #sentinel控制台端口，默认8719，假如被占用会自动从8719开始递增，直到找到可用的端口为止
      datasource: # 配置sentinel的持久化
        ds1:
          nacos: #这里以nacos作为持久化层，当然也可以用数据库等其他组件来存储
            server-addr: localhost:8848 # nacos服务注册中心
            data-id: cloudalibaba-sentinel-service-flow-rule # 持久化文件名
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow # 代表的是流控规则

server:
  port: 8401

#设置ribbon要调用的服务地址
service-protocol: http
service-url: nacos-payment-provider

#激活sentinel对feign的集成
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"